import type { SocData } from "./types";

export const fallbackSocData: SocData = {
  entities: [
    {
      entity_id: "device:WS-04821",
      entity_type: "device",
      display_name: "WS-04821",
      risk_score: 100,
      risk_band: "critical",
      last_seen_at: "2026-05-19T09:21:00Z",
      top_risk_reasons: [
        "Endpoint malware/process alert on analyst workstation",
        "Lateral movement pattern within 10 minutes",
        "Outbound connection to threat-intel IP",
      ],
      recommended_action: "Isolate WS-04821, capture memory, and block outbound indicators.",
    },
    {
      entity_id: "user:jsmith",
      entity_type: "user",
      display_name: "Jordan Smith",
      risk_score: 95,
      risk_band: "critical",
      last_seen_at: "2026-05-19T09:18:00Z",
      top_risk_reasons: [
        "Privileged login anomaly outside business hours",
        "Access to payment-system asset",
        "Badge/digital location mismatch",
      ],
      recommended_action: "Disable sessions, rotate credentials, and validate payment-system access.",
    },
    {
      entity_id: "vendor:payroll-sftp",
      entity_type: "vendor",
      display_name: "Payroll SFTP Vendor",
      risk_score: 72,
      risk_band: "high",
      last_seen_at: "2026-05-19T09:10:00Z",
      top_risk_reasons: [
        "Vendor account accessing sensitive asset",
        "Repeated failed logins before successful access",
      ],
      recommended_action: "Suspend vendor token and require out-of-band verification.",
    },
    {
      entity_id: "asset:PAY-DB-01",
      entity_type: "asset",
      display_name: "PAY-DB-01",
      risk_score: 68,
      risk_band: "high",
      last_seen_at: "2026-05-19T09:18:00Z",
      top_risk_reasons: ["Critical payment database touched by anomalous user and device."],
      recommended_action: "Review database audit logs and snapshot critical tables.",
    },
  ],
  incidents: [
    {
      incident_id: "INC-PAYMENT-001",
      severity: "critical",
      summary:
        "Compromised vendor access correlated with privileged account anomaly, payment-system access, endpoint alert, lateral movement, and threat-intel outbound traffic.",
      started_at: "2026-05-19T09:04:00Z",
      last_seen_at: "2026-05-19T09:21:00Z",
      entities_involved: ["vendor:payroll-sftp", "user:jsmith", "device:WS-04821"],
      target_assets: ["PAY-DB-01", "PAY-APP-02"],
      mitre_techniques: ["T1078", "T1021", "T1059", "T1041"],
    },
  ],
  triage: {
    incident_id: "INC-PAYMENT-001",
    severity: "critical",
    summary:
      "Active payment-system attack chain: vendor compromise led to suspicious privileged access, endpoint execution, lateral movement, and outbound traffic to a known bad IP.",
    target_assets: ["PAY-DB-01", "PAY-APP-02"],
    entities_involved: ["vendor:payroll-sftp", "user:jsmith", "device:WS-04821"],
    mitre_techniques: ["T1078", "T1021", "T1059", "T1041"],
    evidence: {
      event_count: 6,
      lineage: "raw.security_events -> stg_soc_security_events -> mart_soc_incident_timelines",
    },
    recommended_next_steps: [
      "Contain WS-04821 and revoke jsmith privileged sessions.",
      "Disable the payroll vendor integration until access is verified.",
      "Block outbound indicators at egress controls and search for reuse.",
      "Preserve payment-system audit logs for incident response and PCI evidence.",
    ],
    timeline: [
      {
        event_id: "soc-001",
        event_time: "2026-05-19T09:04:00Z",
        source_system: "vendor_access",
        event_type: "third_party_login",
        action: "login_success",
        severity: "medium",
        asset_id: "PAY-APP-02",
        asset_name: "Payment Application",
        src_ip: "198.51.100.44",
        dest_ip: "10.40.2.20",
        mitre_technique: "T1078",
        rule_explanation: "Vendor account accessed a sensitive payment asset.",
      },
      {
        event_id: "soc-002",
        event_time: "2026-05-19T09:08:00Z",
        source_system: "iam",
        event_type: "privileged_login",
        action: "login_success",
        severity: "high",
        asset_id: "PAY-DB-01",
        asset_name: "Payment Database",
        src_ip: "10.12.4.18",
        dest_ip: "10.40.2.10",
        mitre_technique: "T1078",
        rule_explanation: "Privileged access occurred outside the user's normal role/time baseline.",
      },
      {
        event_id: "soc-003",
        event_time: "2026-05-19T09:12:00Z",
        source_system: "endpoint",
        event_type: "process_alert",
        action: "encoded_powershell",
        severity: "critical",
        asset_id: "WS-04821",
        asset_name: "Analyst Workstation",
        src_ip: "10.12.4.18",
        dest_ip: null,
        mitre_technique: "T1059",
        rule_explanation: "Endpoint process tree matched suspicious command execution.",
      },
      {
        event_id: "soc-004",
        event_time: "2026-05-19T09:16:00Z",
        source_system: "network",
        event_type: "lateral_movement",
        action: "smb_session",
        severity: "high",
        asset_id: "PAY-APP-02",
        asset_name: "Payment Application",
        src_ip: "10.12.4.18",
        dest_ip: "10.40.2.20",
        mitre_technique: "T1021",
        rule_explanation: "Workstation reached payment application shortly after privileged login.",
      },
      {
        event_id: "soc-005",
        event_time: "2026-05-19T09:21:00Z",
        source_system: "threat_intel",
        event_type: "outbound_indicator_match",
        action: "egress_connection",
        severity: "critical",
        asset_id: "WS-04821",
        asset_name: "Analyst Workstation",
        src_ip: "10.12.4.18",
        dest_ip: "203.0.113.77",
        mitre_technique: "T1041",
        rule_explanation: "Outbound destination matched a known threat-intel indicator.",
      },
    ],
  },
  qnaTemplates: [
    {
      question_id: "critical_entities_now",
      question: "Which entities are critical right now?",
    },
    {
      question_id: "privileged_payment_after_hours",
      question: "Show privileged payment-system access outside business hours.",
    },
    {
      question_id: "vendor_sensitive_access",
      question: "Which vendors touched sensitive assets this week?",
    },
  ],
  qnaAnswers: [
    {
      question_id: "critical_entities_now",
      question: "Which entities are critical right now?",
      answer_rows: [
        { entity_id: "device:WS-04821", risk_score: 100, risk_band: "critical" },
        { entity_id: "user:jsmith", risk_score: 95, risk_band: "critical" },
      ],
    },
    {
      question_id: "privileged_payment_after_hours",
      question: "Show privileged payment-system access outside business hours.",
      answer_rows: [
        { user_id: "jsmith", asset_id: "PAY-DB-01", event_time: "2026-05-19T09:08:00Z" },
      ],
    },
    {
      question_id: "vendor_sensitive_access",
      question: "Which vendors touched sensitive assets this week?",
      answer_rows: [
        { vendor: "payroll-sftp", asset_id: "PAY-APP-02", action: "login_success" },
      ],
    },
  ],
  compliance: [
    {
      framework: "PCI-DSS",
      controls: [
        {
          framework: "PCI-DSS",
          control_id: "10.2",
          control_name: "Audit logs capture privileged access to cardholder systems",
          evidence_count: 6,
          latest_evidence_at: "2026-05-19T09:21:00Z",
          lineage: "marts.mart_soc_compliance_evidence",
        },
        {
          framework: "PCI-DSS",
          control_id: "12.10",
          control_name: "Incident response evidence is retained",
          evidence_count: 1,
          latest_evidence_at: "2026-05-19T09:21:00Z",
          lineage: "marts.mart_soc_incident_timelines",
        },
      ],
    },
    {
      framework: "SOC2",
      controls: [
        {
          framework: "SOC2",
          control_id: "CC7.2",
          control_name: "Security events are monitored and evaluated",
          evidence_count: 6,
          latest_evidence_at: "2026-05-19T09:21:00Z",
          lineage: "marts.mart_soc_risk_events",
        },
        {
          framework: "SOC2",
          control_id: "CC7.4",
          control_name: "Incident response actions are documented",
          evidence_count: 4,
          latest_evidence_at: "2026-05-19T09:21:00Z",
          lineage: "marts.mart_soc_incident_timelines",
        },
      ],
    },
  ],
};
