-- Phase 7A: SOC incident mutable state
-- Separates live operational state from the dbt-managed mart read-models.
-- The mart_soc_incident_timelines view is read-only (regenerated by dbt).
-- This schema holds analyst actions and status changes.

CREATE SCHEMA IF NOT EXISTS soc;

-- ──────────────────────────────────────────────────────────────────────────────
-- Incident state (one row per incident; version for optimistic locking)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS soc.incident_state (
  incident_id  TEXT PRIMARY KEY,
  status       TEXT NOT NULL DEFAULT 'open',
  -- open | investigating | contained | resolved | closed
  severity     TEXT,
  assignee     TEXT,   -- display name of assigned analyst
  notes        TEXT,
  acknowledged BOOLEAN NOT NULL DEFAULT false,
  investigated_entities TEXT[] NOT NULL DEFAULT '{}',
  completed_steps TEXT[] NOT NULL DEFAULT '{}',
  version      INTEGER NOT NULL DEFAULT 1,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by   TEXT    -- user_id of last modifier
);

ALTER TABLE soc.incident_state
  ADD COLUMN IF NOT EXISTS acknowledged BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS investigated_entities TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS completed_steps TEXT[] NOT NULL DEFAULT '{}';

-- ──────────────────────────────────────────────────────────────────────────────
-- Incident actions audit log (append-only)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS soc.incident_actions (
  action_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id  TEXT NOT NULL,
  actor        TEXT NOT NULL,  -- user_id
  action_type  TEXT NOT NULL,
  -- status_change | assignee_change | note_added | severity_change | acknowledged
  -- entity_investigated | step_completed | step_reopened
  old_value    JSONB,
  new_value    JSONB NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_soc_incident_actions_incident
  ON soc.incident_actions(incident_id, created_at DESC);

-- ──────────────────────────────────────────────────────────────────────────────
-- Seed the known demo incident so PATCH requests have a row to update.
-- The incident_id must match what mart_soc_incident_timelines returns.
-- ──────────────────────────────────────────────────────────────────────────────
INSERT INTO soc.incident_state (incident_id, status, severity, assignee, notes, version, updated_by)
VALUES ('INC-PAYMENT-001', 'open', 'critical', 'Unassigned', NULL, 1, NULL)
ON CONFLICT (incident_id) DO NOTHING;
